# make sure the host drivers >= cuda11.8 corresponding version
FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive

# Setup time zone and locale data (necessary for SSL and HTTPS packages)
RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install --no-install-recommends -y \
    tzdata \
    locales \
    keyboard-configuration \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG=en_US.UTF-8

ENV LANG=en_US.UTF-8

# Install common tools and ubuntu graphic desktop and vnc+novnc
RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install --no-install-recommends -y \
    # common depends
    ca-certificates \
    curl \
    sudo \
    software-properties-common \
    python3-pip \
    # graphics desktop depends
    dbus-x11 \
    novnc \
    openssh-server \
    supervisor \
    x11vnc xvfb \
    xfce4 xfce4-goodies \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /root

ADD startup.sh ./
ADD supervisord.conf ./

EXPOSE 5900
EXPOSE 22
