ARG UBUNTU_VERSION=22.04
ARG NVIDIA_CUDA_VERSION=11.8.0
FROM nvidia/cuda:${NVIDIA_CUDA_VERSION}-devel-ubuntu${UBUNTU_VERSION}
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install --no-install-recommends -y \
    git \
    wget \
    cmake \
    ninja-build \
    build-essential \
    python3.10-dev \
    python3-pip \
    libgl1-mesa-glx \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /root/
RUN git clone https://github.com/nv-tlabs/NKSR.git

RUN cd NKSR && pip install nksr -f https://nksr.huangjh.tech/whl/torch-2.0.0+cu118.html
RUN wget --no-check-certificate https://nksr.huangjh.tech/ks.pth -P /root/.cache/torch/hub/checkpoints/
